@WayMatcherAPI_HostAddress = http://localhost:5000

### Register a new user
POST {{WayMatcherAPI_HostAddress}}/api/login/loginuser
Content-Type: application/json
Accept: application/json
{
  "Username": "johndoe",
  "Email": "",
  "Password": "password123"
}