@WayMatcherAPI_HostAddress = http://localhost:5197

### Register a new user
POST {{WayMatcherAPI_HostAddress}}/api/MfA/MfAInput
Content-Type: application/json
Accept: application/json
{
    "Token": "asdf",
    "Username": "asdf",
    "Email": ""
}