// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Street { get; set; }

    public string Country { get; set; }

    public string CountryCode { get; set; }

    public string Region { get; set; }

    public string State { get; set; }

    public double? Longitude { get; set; }

    public double? Latitude { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public int? StatusId { get; set; }

    public virtual Status Status { get; set; }

    public virtual ICollection<Stop> Stops { get; set; } = new List<Stop>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}