// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class ChatMessage
{
    public int ChatMessageId { get; set; }

    public string Message { get; set; }

    public DateTime? Timestamp { get; set; }

    public int? UserId { get; set; }

    public int? EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}