// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class ConfirmationStatus
{
    public int ConfirmationStatusId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Invite> Invites { get; set; } = new List<Invite>();
}