// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class EventMember
{
    public int MemberId { get; set; }

    public int? EventMemberTypeId { get; set; }

    public int? UserId { get; set; }

    public int? EventId { get; set; }

    public int? StatusId { get; set; }

    public virtual Event Event { get; set; }

    public virtual EventMemberType EventMemberType { get; set; }

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }
}