// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class Event
{
    public int EventId { get; set; }

    public int? EventTypeId { get; set; }

    public int? FreeSeats { get; set; }

    public string Description { get; set; }

    public DateTime? StartTimestamp { get; set; }

    public int? ScheduleId { get; set; }

    public int? StatusId { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual ICollection<EventMember> EventMembers { get; set; } = new List<EventMember>();

    public virtual EventType EventType { get; set; }

    public virtual ICollection<Invite> Invites { get; set; } = new List<Invite>();

    public virtual Schedule Schedule { get; set; }

    public virtual Status Status { get; set; }

    public virtual ICollection<Stop> Stops { get; set; } = new List<Stop>();
}