// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class EventMemberType
{
    public int EventMemberTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<EventMember> EventMembers { get; set; } = new List<EventMember>();
}