// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WayMatcherBL.Models
{
    public partial class FN_GetEventsByMemberUserIdResult
    {
        public int Event_ID { get; set; }
        public int? EventType_ID { get; set; }
        public int? Free_Seats { get; set; }
        public string Description { get; set; }
        public DateTime? Start_Timestamp { get; set; }
        public int? Schedule_ID { get; set; }
        public int? Status_ID { get; set; }
        public int? EventOwner_ID { get; set; }
    }
}
