// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class Invite
{
    public int InviteId { get; set; }

    public int? ConfirmationStatusId { get; set; }

    public bool? IsRequest { get; set; }

    public int? EventId { get; set; }

    public int? UserId { get; set; }

    public virtual ConfirmationStatus ConfirmationStatus { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}