// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WayMatcherBL.Models;

namespace WayMatcherBL.Models
{
    public partial interface IWayMatcherContextProcedures
    {
        Task<int> LogAuditEntryAsync(string message, string entity_Type, int? entity_ID, int? user_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
