// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public bool? Read { get; set; }

    public string Message { get; set; }

    public string EntityType { get; set; }

    public int? EntityId { get; set; }

    public int? UserId { get; set; }

    public virtual User User { get; set; }
}