// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class Rating
{
    public int RatingId { get; set; }

    public string RatingText { get; set; }

    public int? RatingValue { get; set; }

    public int? RatedUserId { get; set; }

    public int? UserWhoRatedId { get; set; }

    public int? StatusId { get; set; }

    public virtual User RatedUser { get; set; }

    public virtual Status Status { get; set; }

    public virtual User UserWhoRated { get; set; }
}