// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class Stop
{
    public int StopId { get; set; }

    public int? StopSequenceNumber { get; set; }

    public int? AddressId { get; set; }

    public int? EventId { get; set; }

    public virtual Address Address { get; set; }

    public virtual Event Event { get; set; }
}