// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Firstname { get; set; }

    public string Name { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string EMail { get; set; }

    public string Telephone { get; set; }

    public string AdditionalDescription { get; set; }

    public bool? LicenseVerified { get; set; }

    public byte[] ProfilePicture { get; set; }

    public DateTime? CreationDate { get; set; }

    public int? AddressId { get; set; }

    public int? RoleId { get; set; }

    public int? StatusId { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<Audit> Audits { get; set; } = new List<Audit>();

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual ICollection<EventMember> EventMembers { get; set; } = new List<EventMember>();

    public virtual ICollection<Invite> Invites { get; set; } = new List<Invite>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Rating> RatingRatedUsers { get; set; } = new List<Rating>();

    public virtual ICollection<Rating> RatingUserWhoRateds { get; set; } = new List<Rating>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual Status Status { get; set; }

    public virtual ICollection<VehicleMapping> VehicleMappings { get; set; } = new List<VehicleMapping>();
}