// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class VehicleMapping
{
    public int VehicleMappingId { get; set; }

    public decimal? FuelMilage { get; set; }

    public string AdditionalInfo { get; set; }

    public string LicensePlate { get; set; }

    public int? VehicleId { get; set; }

    public int? UserId { get; set; }

    public int? StatusId { get; set; }

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}