// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public string Model { get; set; }

    public int? Seats { get; set; }

    public int? YearOfManufacture { get; set; }

    public string ManufacturerName { get; set; }

    public int? StatusId { get; set; }

    public virtual Status Status { get; set; }

    public virtual ICollection<VehicleMapping> VehicleMappings { get; set; } = new List<VehicleMapping>();
}