// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WayMatcherBL.Models;

public partial class VwEventDetail
{
    public int EventId { get; set; }

    public int? EventTypeId { get; set; }

    public int? FreeSeats { get; set; }

    public string Description { get; set; }

    public DateTime? StartTimestamp { get; set; }

    public int? ScheduleId { get; set; }

    public int? StatusId { get; set; }

    public int? ScheduleScheduleId { get; set; }

    public string CronSchedule { get; set; }

    public int? StopId { get; set; }

    public int? StopSequenceNumber { get; set; }

    public int? AddressId { get; set; }

    public int? StopEventId { get; set; }

    public int? AddressAddressId { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Street { get; set; }

    public string Country { get; set; }

    public string CountryCode { get; set; }

    public string Region { get; set; }

    public string State { get; set; }

    public double? Longitude { get; set; }

    public double? Latitude { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public int? MemberId { get; set; }

    public int? EventMemberTypeId { get; set; }

    public int? UserId { get; set; }

    public int? EventMemberEventId { get; set; }

    public int? EventMemberStatusId { get; set; }

    public int? InviteId { get; set; }

    public int? ConfirmationStatusId { get; set; }

    public bool? IsRequest { get; set; }

    public int? InviteEventId { get; set; }

    public int? InviteUserId { get; set; }
}