// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using WayMatcherBL.Models;

namespace WayMatcherBL.Models
{
    public partial class WayMatcherContext
    {

        [DbFunction("FN_GetEventsByMemberUserId", "WayMatcher")]
        public IQueryable<FN_GetEventsByMemberUserIdResult> FN_GetEventsByMemberUserId(int? UserID)
        {
            return FromExpression(() => FN_GetEventsByMemberUserId(UserID));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FN_GetEventsByMemberUserIdResult>().HasNoKey();
        }
    }
}
